name: Build and Release Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        id: flutter-action
        with:
          architecture: x64
      - run: |
          git config --global --add safe.directory /opt/hostedtoolcache/flutter/${{ steps.flutter-action.outputs.CHANNEL }}-${{ steps.flutter-action.outputs.VERSION }}-${{ steps.flutter-action.outputs.ARCHITECTURE }}
          flutter --version
          
      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Extract Version
        id: get_version
        run: |
          version=$(grep '^version:' pubspec.yaml | awk '{print $2}')
          echo "version=$version" >> $GITHUB_ENV
          echo "Version extracted: $version"

      - name: Upload Release Artifact to GitHub
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ env.version }}
          name: Nav Dashboard v${{ env.version }}
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          artifactContentType: application/vnd.android.package-archive
          draft: false
          prerelease: false
