name: Build and Release Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      version: 1.0.0 # Define the version here or dynamically fetch it in a script

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter environment
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: latest

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Build Android APK
      - name: Build APK
        run: flutter build apk --release

      # Step 5: Upload Release Artifact to GitHub
      - name: Upload Release Artifact to GitHub
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ env.version }}
          name: Nav Dashboard v${{ env.version }}
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          artifactContentType: application/vnd.android.package-archive
          draft: false
          prerelease: false
